### ISSUE TITLE
typo on installation page

### ISSUE THREAD

**Issue by nimgould** [kul-optec/QPALM#1]
This is very minor - 

In the C/C++ installation section of 

https://kul-optec.github.io/QPALM/Doxygen/installation-md.html

the 4th line

cmake --install build/QPALM/LADEL --prefix /usr/local

should read

cmake --install build/LADEL --prefix /usr/local

This is correctly stated for the shared library version just below

Thanks for providing the package, very useful.

Nick

**Comment by tttapa** [comment]
The instructions have been updated, thanks for letting us know!
