### ISSUE TITLE
instructions to run the examples

### ISSUE THREAD

**Issue by nimgould** [kul-optec/QPALM#2]
I followed the instructions to build the libraries, and all seems fine.
However, I haven't yet found a way to run the examples you provide.
(please excuse me, I am not a cmake expert).

Naively I moved into the examples/c directory,  and compiled via

gcc -o qpalm_demo qpalm_demo.c -lqpalm -lladel -lladel_amd -lm

Unfortunately, running the binary qpalm_demo generates a segfault.

Is there an "official" way to run the tests to see that the installation works?
It would be useful to include this on the "installation" page.

Thank you

Nick

PS. This is Linux Mint 20.1, 
The C compiler identification is GNU 9.4.0
The CXX compiler identification is GNU 9.4.0

**Comment by tttapa** [comment]
If you have a folder containing the file `qpalm_demo.c`, you can add the following `CMakeLists.txt` file in the same folder:
```cmake
# Standard CMake preamble
cmake_minimum_required(VERSION 3.20)
project(qpalm_demo)

# Find the QPALM installation
find_package(QPALM REQUIRED)

# Compile the qpalm_demo.c file into an executable
add_executable(qpalm_demo "qpalm_demo.c")
# Link it to the QPALM library (takes care of compiler flags and linking)
target_link_libraries(qpalm_demo PRIVATE QPALM::qpalm)
```
Then you can build and run it using:
```sh
cmake -Bbuild -S.
cmake --build build -j
./build/qpalm_demo # exact location depends on the default generator for your system
```
If you add the verbose (`-v`) flag to the build command, you'll see that CMake automatically includes some extra flags when compiling your program:
```sh
gcc -DCOMPILE_NONCONVEX -DDAMD -DLADEL_64BIT_INDICES -DPRINTING -DPROFILING -DQPALM_VERSION_MAJOR=1 -DQPALM_VERSION_MINOR=0 -DQPALM_VERSION_PATCH=1 -DQPALM_VERSION_STR=\"1.0.1\" -DSIMPLE_COL_COUNTS -DUSE_LADEL ...
```
If you don't pass the same options as the ones used when building QPALM, the struct layouts and integer sizes etc. will be different, which explains the segfault you got. To make sure that the options match, I'd recommend using CMake, but if you add these flags to your manual Makefile it should work as well.

**Comment by nimgould** [comment]
Perfect. Many thanks, Pieter. Just what I needed.
