### ISSUE TITLE
Issues installing QPALM in Julia

### ISSUE THREAD

**Issue by alexe15** [kul-optec/QPALM#3]
Hi, I tried to install QPALM for Julia, but the package seems to be unavailable. The only one which I can find is Julia_jll, but when I tried this one I can't run the demo example (https://kul-optec.github.io/QPALM/Doxygen/examples_2julia_2qpalm_julia_demo_8jl-example.html, error message: the Model() function is not defined in this package). 

I also tried to build the package from the sources as described here (https://kul-optec.github.io/QPALM/Doxygen/installation-md.html), but then I get the following error:

ERROR: Unsatisfiable requirements detected for package QPALM_jll [ffff4089]:
 QPALM_jll [ffff4089] log:
 ├─possible versions are: [0.1.0-0.1.1, 0.2.0, 0.3.0, 1.0.0] or uninstalled
 ├─restricted to versions 0.1.1-0.1 by QPALM [6c3e646c], leaving only versions 0.1.1
 │ └─QPALM [6c3e646c] log:
 │   ├─possible versions are: 0.1.0 or uninstalled
 │   └─QPALM [6c3e646c] is fixed to version 0.1.0
 └─restricted by julia compatibility requirements to versions: 0.3.0 or uninstalled — no versions left
 
Do you have any idea what the problem could be? I'm using Julia 1.5.3. on Debian.

Thank you!

**Comment by tttapa** [comment]
There has been some delay in adding the package to the general repository. In the mean time, you can install QPALM directly from GitHub:

Open a Julia console and press `]` to enter Pkg mode, then enter:
```sh
add https://github.com/kul-optec/QPALM.jl#main
```

**Comment by alexe15** [comment]
Thank you for your quick answer! Unfortunately I still get the error 

ERROR: Unsatisfiable requirements detected for package QPALM_jll [ffff4089]:
 QPALM_jll [ffff4089] log:
 ├─possible versions are: [0.1.0-0.1.1, 0.2.0, 0.3.0, 1.0.0] or uninstalled
 ├─restricted to versions 1 by QPALM [6c3e646c], leaving only versions 1.0.0
 │ └─QPALM [6c3e646c] log:
 │   ├─possible versions are: 1.0.0 or uninstalled
 │   └─QPALM [6c3e646c] is fixed to version 1.0.0
 └─restricted by julia compatibility requirements to versions: 0.3.0 or uninstalled — no versions left

once I run the above command.

**Comment by tttapa** [comment]
> I'm using Julia 1.5.3. on Debian.

> restricted by julia compatibility requirements to versions: 0.3.0 or uninstalled — no versions left

Aha, I see, QPALM_jll only supports Julia >=1.6. It might work if you lower that requirement in the `QPALM/interfaces/julia/build_tarbals.jl` file and then build it from source.

**Comment by alexe15** [comment]
Works, thank you @tttapa! I installed the latest Julia version - I'm wondering why the Julia version is so old in the official Debian repositories...
